### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by PhilippTakacs** [Forescout/project-memoria-detector#1]
Hi

Because [Python2 is EOL](https://www.python.org/doc/sunset-python-2/) it would be nice to also support Python3.

As far as I see this only requires to change [this Line](https://github.com/Forescout/project-memoria-detector/blob/main/project-memoria-detector.py#L188) to `src_port = RandShort()._fix()//2+2**15`

**Comment by standash** [comment]
Hi,

I have pushed a new commit that adds the Python 3 support.
