### ISSUE TITLE
all devices showing appears to be down

### ISSUE THREAD

**Issue by jonshock** [Forescout/project-memoria-detector#11]
Tried the project against several devices in network but keep getting "appears to be down" the devices dont have firewall enabled. Anyone experience this while running? And yes the devices are online.

**Comment by standash** [comment]
Hi @jonshock, thank you for your comment! I cannot reproduce your issue in my environment. Could you please provide more details on how you run the script and what OS are you using? Thanks!

**Comment by jonshock** [comment]
I am using windows 10. Python version 3.9.6 and the lastest from scapy master. As of 8/9/2021. I just run it from "bash" via python with the ip I want to target.

**Comment by standash** [comment]
Thanks, try running it with the newly added "-st" option, maybe it will help. Otherwise, I can only suggest to run the script from a Linux box.

**Comment by jonshock** [comment]
Yeah still getting appears to be down - I'll try and beg management to let me put a Linux box on network. Thanks for your help.
