### ISSUE TITLE
No such device error

### ISSUE THREAD

**Issue by ldwedari** [Forescout/project-memoria-detector#2]
Thanks for creating this script.

I'm getting this error. It seems that the interface eth0 that I'm passing (retrieved with ifconfig in the target machine) is not the right one:
```
~/project-memoria-detector$ sudo -E python project-memoria-detector.py -ip_dst 192.168.1.2 -p 443 -i eth0
192.168.1.2
        ICMP fingerprint => failed to determine the TCP/IP stack (reason: No match)
ERROR: [Errno 19] No such device
Exception IOError: IOError(19, 'No such device') in <bound method L3PacketSocket.__del__ of <scapy.arch.linux.L3PacketSocket object at 0x7fda0de7ecd0>> ignored
        TCP fingerprint => failed to determine the TCP/IP stack (reason: No match)

```
I'm running the script from a VirtualBox machine with Debian.

Can I trust the no match messages?

**Comment by standash** [comment]
Hi @ldwedari ,

I have created a new commit that slightly improves the error messages of the script. However, I believe that you are specifying a wrong interface name (I think, in your case 'No match' will change to 'No reply').

**Comment by ldwedari** [comment]
Thank for replying. Indeed, it is still not working. I don't really understand why I even need to provide the network interface in the destination device, I guess I leave it for now. Hopefully there will be an easier way to check the TCP stack for this vulnerabilities in the future.
