### ISSUE TITLE
No Module named scapy.all

### ISSUE THREAD

**Issue by john2exonets** [Forescout/project-memoria-detector#3]
When I try to run this from a Mac, I get this error:

`mba:project-memoria-detector-main john$ sudo -E python project-memoria-detector.py -ip_dst 10.44.45.32 -p 443 -i en3
Traceback (most recent call last):
  File "project-memoria-detector.py", line 24, in <module>
    from scapy.all import conf, send, sr1, IP, ICMP, TCP, Raw, RandShort
ImportError: No module named scapy.all`

I assume there is something I need to install? Specific version required?

**Comment by standash** [comment]
Hi @john2exonets,

Yes, you need to have Scapy installed. Please have a look at the "Dependencies" section of the README.md, or follow this link: https://scapy.readthedocs.io/en/latest/installation.html.
