### ISSUE TITLE
Broadcom TCP Stack

### ISSUE THREAD

**Issue by frakman1** [Forescout/project-memoria-detector#4]
What TCP stack does Broadcom based routers, modems and gateways use and is it currently one of the ones detected?

**Comment by standash** [comment]
I am afraid the answer to this question is not trivial. Do you have a specific device model/manufacturer in mind?

**Comment by frakman1** [comment]
Something like [this](https://www.amazon.com/dp/B07DY16W2Z) that uses the Broadcom BCM3390 chipset 

<p align="center">
<img src="https://user-images.githubusercontent.com/5826484/114600757-b3129680-9c62-11eb-976a-250e9c31f708.png">
</p>

**Comment by standash** [comment]
Sorry, I have never seen those before, so I cannot be of help.

**Comment by nealmcb** [comment]
Can you tell us how it behaves as a target of this software? That might help others help you.

**Comment by frakman1** [comment]
Or something like [this](https://deviwiki.com/wiki/Cisco_DPC3929CAD). A very popular Comcast/Xfinity field-deployed router.
It uses the Broadband BCM3383Z chipset.

<p align="center">
<img src="https://user-images.githubusercontent.com/5826484/114610785-4c937580-9c6e-11eb-9e8a-9bfbedefecc1.png">
</p>

**Comment by frakman1** [comment]
> Can you tell us how it behaves as a target of this software? That might help others help you.

The behavior is that it is unrecognized.

```
$ sudo python project-memoria-detector.py  192.168.0.1
	Failed to determine the TCP/IP stack for host 192.168.0.1 (reason: No match)
```

There are millions of these types of devices deployed in North America and around the world. It would be useful to know its TCP IP stack profile

**Comment by standash** [comment]
> The behavior is that it is unrecognized.

Then, most likely, the script does not yet support this particular stack. Feel free to add the fingerprint and make a merge request.

**Comment by frakman1** [comment]
The `-v` option does not print out the fingerprint of unknown stacks (possible improvement opportunity here)
I added a print and it looks like this:

```
tcp_opts:[('MSS', 1938), ('NOP', None), ('NOP', None), ('SAckOK', ''), ('NOP', None), ('WScale', 6)]
```

**Comment by frakman1** [comment]
I similar device (same chipset) had a signature of:

```
tcp_opts: [('MSS', 1460), ('NOP', None), ('NOP', None), ('SAckOK', ''), ('NOP', None), ('WScale', 6)]
```

**Comment by standash** [comment]
Hi @frakman1. thanks for your message! The purpose if this is script is to fingerprint known tcp/ip stacks, and not the hardware. For example, the chipset that you mention is a general purpose one, therefore (in theory) any vendor can use it for its own device an deploy any tcp/ip stack there. Unless you really know what is the name of the stack that is running there, this is not going to be useful (also, TCP options fingerprint has weak discriminative power, and the second one looks rather generic).  In short, the question we try to answer is "what known stack is running on this device?" rather than "what is a fingerprint of this device?".

**Comment by frakman1** [comment]
My research shows that it is an eCos TCP/IP stack but not sure if that's based on OpenBSD or FreeBSD. It's meant to be modular in terms of TCP IP stack support. 
If I had access to the source code, are there any tell-tale signs I could look for?

**Comment by standash** [comment]
@frakman1, that's a good question indeed. Before digging into the source code I would first try to see if your device issues any banners that clearly say what the stack is (e.g., http, ssh, ftp, ...). If this fails, then the best way is to reverse engineer the firmware. If you do have the source code, one way would also to see if there are any implementation quirks that match your device (e.g., have a look at ICMP and TCP Urgent flag fingerprints that we have, for example).

**Comment by frakman1** [comment]
I checked and there are no banners. The nmap TCP fingerprint result looks like this:

```
TCP/IP fingerprint:
SCAN(V=7.91SVN%E=4%D=4/14%OT=22%CT=1%CU=42087%PV=N%DS=6%DC=I%G=N%TM=607716B5%P=x86_64-unknown-linux-gnu)
SEQ(SP=100%GCD=1%ISR=FE%TI=I%CI=I%II=I%SS=S%TS=7)
OPS(O1=M796NW0NNT11%O2=M796NW0NNT11%O3=M796NW0NNT11%O4=M796NW0NNT11%O5=M796NW0NNT11%O6=M796NNT11)
WIN(W1=43E0%W2=4110%W3=423C%W4=4074%W5=4180%W6=403D)
ECN(R=Y%DF=Y%T=40%W=4470%O=M796NW0%CC=N%Q=)
T1(R=Y%DF=Y%T=40%S=O%A=S+%F=AS%RD=0%Q=)
T2(R=N)
T3(R=Y%DF=Y%T=40%W=403D%S=O%A=S+%F=AS%O=M796NW0NNT11%RD=0%Q=)
T4(R=Y%DF=N%T=40%W=0%S=A%A=Z%F=R%O=%RD=0%Q=)
T5(R=Y%DF=N%T=40%W=0%S=Z%A=S+%F=AR%O=%RD=0%Q=)
T6(R=Y%DF=N%T=40%W=0%S=A%A=Z%F=R%O=%RD=0%Q=)
T7(R=Y%DF=N%T=40%W=0%S=Z%A=S%F=AR%O=%RD=0%Q=)
U1(R=Y%DF=N%T=40%IPL=38%UN=0%RIPL=G%RID=G%RIPCK=G%RUCK=0%RUD=G)
IE(R=Y%DFI=S%T=40%CD=S)
```

and the guessed OS is an eCos/FreeBSD variant.

Only ports 80, 443, 22 and UDP port 161 (SNMP) are seen.

**Comment by standash** [comment]
Thanks for your response. @frakman1. This still looks a bit too vague to me and nmap is known to be not precise there, therefore I would not add this fingerprint just yet. We will eventually add support for eCos, so stay tuned.
