### ISSUE TITLE
Use "iptables -I" instead of "iptables -A"

### ISSUE THREAD

**Issue by uwedisch** [Forescout/project-memoria-detector#9]
Hello,

please use "iptables -I" instead of "iptables -A" in cou Python code because "-A" appends the created rule at the end of the OUTPUT table.  This results possibly in an appended rule which is never reached, and therefore useless, and because of this, detection result could degrade.

Please use "-I" without positional parameter which places the rule on top of the other OUTPUT rules making the rule to work always as intended.

Many thanks.

**Comment by standash** [comment]
Hi @uwedisch, sorry for the late reply. Thanks a lot for your comment, I applied your suggestion in this commit: https://github.com/Forescout/project-memoria-detector/commit/8a24217edba8ecc5fb3bd008fcf6010f181783d5
